/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.prog2.wordcloud;

import org.junit.jupiter.api.Disabled;

class AppTest {
    @Disabled
    void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
